name       : libvncserver
version    : 0.9.11
release    : 5
source     :
    - https://github.com/LibVNC/libvncserver/archive/LibVNCServer-0.9.11.tar.gz : 193d630372722a532136fd25c5326b2ca1a636cbb8bf9bb115ef869c804d2894
license    : GPL-2.0-or-later
component  : programming.library
summary    : VNC Server Library
description: |
    A library for easy implementation of a VNC server.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gnutls)
    - pkgconfig(libturbojpeg)
setup      : |
    %autogen --disable-static
build      : |
    %make
install    : |
    %make_install
