name       : libvncserver
version    : 0.9.13
release    : 8
source     :
    - https://github.com/LibVNC/libvncserver/archive/LibVNCServer-0.9.13.tar.gz : 0ae5bb9175dc0a602fe85c1cf591ac47ee5247b87f2bf164c16b05f87cbfa81a
license    : GPL-2.0-or-later
component  : programming.library
summary    : VNC Server Library
description: |
    A library for easy implementation of a VNC server.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libgcrypt)
    - pkgconfig(libturbojpeg)
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
