name       : libvncserver
version    : 0.9.10
release    : 1
source     :
    - https://github.com/LibVNC/libvncserver/archive/LibVNCServer-0.9.10.tar.gz : ed10819a5bfbf269969f97f075939cc38273cc1b6d28bccfb0999fba489411f7
license    : GPL-2.0
summary    : VNC Server Library
description: |
    A library for easy implementation of a VNC server.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(gnutls)
    - libjpeg-turbo-devel
setup      : |
    ./autogen.sh --prefix=/usr
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
