name       : libvncserver
version    : 0.9.14
release    : 9
source     :
    - https://github.com/LibVNC/libvncserver/archive/LibVNCServer-0.9.14.tar.gz : 83104e4f7e28b02f8bf6b010d69b626fae591f887e949816305daebae527c9a5
homepage   :  https://github.com/LibVNC/libvncserver
license    : GPL-2.0-or-later
component  : programming.library
summary    : VNC Server Library
description: |
    A library for easy implementation of a VNC server.
builddeps  :
    - pkgconfig(gtk+-2.0)
    - pkgconfig(libgcrypt)
    - pkgconfig(libturbojpeg)
setup      : |
    %cmake
build      : |
    %make
install    : |
    %make_install
